version: 2.1

commands:

  # Verify we're on one of the "allowed branches" and terminate job in case we aren't
  # Allowed branches are main and test in this scenario
  check_deployment_branch: 
    steps:
      - run:
          name: Assert the current branch is correct
          command: |
            branch=<< pipeline.git.branch >>
            if [ "$branch" != "main" ] &&  [ "$branch" != "test" ]; then
                echo "Branch is not either main or test - will fail"
                (exit -1)
            else
              echo "Branch is either main or test - can continue"
            fi
            
jobs:
  a_build:
    docker: 
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: "echo running job A"

  b_deploy:   
    docker: 
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - check_deployment_branch
      - run:
          name: echo with arg
          command: |
            echo "hello from branch: << parameters.branch_name >>"

workflows:
  workflow:
    jobs:
      - a_build
      - b_deploy:
          requires:
            - a_build
        filters:
          branches:
            only:
              - main
              - test          
